force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/MileStone_Percentage_Completion__c.field-meta.xml
<CustomField>
    <fullName>MileStone_Percentage_Completion__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>MileStone Percentage Complete</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Percentage_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Complete__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Percentage Complete</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MilestoneService.cls
public class MilestoneService {
    
    public static void updateProjectCompletion(List<Milestone__c> newList) {
        Set<Id> milestoneIds = new Set<Id>();
        List<Project__c> projectListToUpdate = new List<Project__c>();
        for(Milestone__c ms : newList) {
            milestoneIds.add(ms.Project__c);
        }

        for(Project__c proj: [SELECT Id, (SELECT Id, MileStone_Percentage_Completion__c FROM Milestones__r) FROM Project__c WHERE Id IN:milestoneIds]) {
            Double projCompletion = 0;
            Integer count = 0;
            for(MileStone__c ms: proj.MileStones__r) {
                if(ms.MileStone_Percentage_Completion__c != null) {
                    projCompletion += ms.MileStone_Percentage_Completion__c;
                }
                count++;
            }
            Double percentageCompletion = projCompletion / count;
            String status = getStatus(percentageCompletion);
            Project__c project = new project__c(Id = proj.Id, Percentage_Complete__c = percentageCompletion, Status__c = status);
            projectListToUpdate.add(project);
        }

        if(!projectListToUpdate.isEmpty()) {
            update projectListToUpdate;
        }

    }

    public static String getStatus(Double percentageCompletion) {
        if(percentageCompletion == 0) {
            return 'Not Started';
        } else if(percentageCompletion == 100) {
            return 'Complete';
        } else {
            return 'In Progress';
        }
    }
}